# This is a simple Azure configuration, which is intended for use
# on applications which do not require cross-platform and
# multiple-GHC-version support. For more information and other
# options, see:
#
# https://docs.haskellstack.org/en/stable/azure_ci/
#
# Copy these contents into the root directory of your Github project in a file
# named azure-pipelines.yml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


variables:
  STACK_ROOT: /home/vsts/.stack


steps:
- task: Cache@2
  inputs:
    key: '"stack-v1" | "$(Agent.OS)" | $(Build.SourcesDirectory)/stack.yaml.lock'
    path: .azure-cache
  displayName: Download Cache
- bash: |
    mkdir -p $STACK_ROOT
    tar -vxzf .azure-cache/stack-root.tar.gz -C /
    mkdir -p .stack-work
    tar -vxzf .azure-cache/stack-work.tar.gz
  displayName: "Unpack cache"
- script: |
    mkdir -p ~/.local/bin
    curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  displayName: Install Stack
- script: |
    export PATH=$HOME/.local/bin:$PATH
    stack --no-terminal --install-ghc test --only-dependencies
  displayName: Build Dependencies
- script: |
    export PATH=$HOME/.local/bin:$PATH
    # Build the package, its tests, and its docs and run the tests
    stack test --haddock --no-haddock-deps
  displayName: Test Package
- bash: |
    mkdir -p .azure-cache
    tar -vczf .azure-cache/stack-root.tar.gz $STACK_ROOT
    tar -vczf .azure-cache/stack-work.tar.gz .stack-work
  displayName: "Pack cache"