#!/bin/bash -e

pname=cv-convert

echo ">>> Building Haddock for $pname"
time stack haddock --no-haddock-deps --fast
doc_root=$(stack path --local-doc-root)/$pname*
du -h "$doc_root"
git branch -D gh-pages || echo "gh-pages branch didn't exist"
git checkout --orphan gh-pages
rm -rf *
cp -r "$doc_root"/* .
git add .
git commit -m "Automatic Haddock commit"
time git push -f -u origin gh-pages
git checkout master