#!/bin/bash

port=5432

isfree=$(netstat -taln | grep $port)

while [[ -n "$isfree" ]]; do
  port=$((port+1))
  isfree=$(netstat -taln | grep "$port")
done

echo "Usable port for DB found: $port"

echo "Starting a docker postgres container..."
docker run --rm --name cv-convert-test-postgres -p "$port":5432 -e POSTGRES_PASSWORD=mysecretpassword -d postgres


# make sure pg is ready to accept connections
until pg_isready -h localhost -p "$port" -U postgres
do
  echo "Waiting for postgres..."
  sleep 2;
done


Cleanup() {
  echo "Stopping the postgres container..."
  docker stop cv-convert-test-postgres
}

echo "Running 'stack test'..."
trap Cleanup EXIT

stack test --flag 'cv-convert:azure' --ta "--postgres-db-config postgresql://postgres:mysecretpassword@localhost:$port/postgres" --ta '--delete-output onpass'

