#!/bin/bash -e

pname=cv-convert

echo ">>> Building Haddock for $pname"
stack haddock --no-haddock-deps --fast
doc_root=$(stack path --local-install-root)/doc/$pname*

git branch -D gh-pages || echo "gh-pages branch didn't exist"
git checkout --orphan gh-pages
rm -rf *
cp -r $(echo $doc_root)/* .
git add .
git commit -m "Automatic Haddock commit"
git push -f -u origin gh-pages
git checkout master